version: "3.9"

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/parser_project/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1]
      - CELERY_BROKER=redis://:Skyrimko234@redis:6379/0
      - CELERY_BACKEND=redis://:Skyrimko234@redis:6379/0
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A parser_project worker --loglevel=info
    volumes:
      - .:/usr/src/app
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1]
      - CELERY_BROKER=redis://:Skyrimko234@redis:6379/0
      - CELERY_BACKEND=redis://:Skyrimko234@redis:6379/0
    depends_on:
      - django
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server --requirepass Skyrimko234




